sonar.projectKey=dorm_system
sonar.projectName=Dorm System
sonar.host.url=http://localhost:9000
sonar.token=sqa_0ecb23afb733d0b504e56f70e2f818076889b9df

sonar.sources=frontend,backend
sonar.exclusions=frontend/node_modules/**,backend/node_modules/**,node_modules/**,frontend/dist/**,backend/dist/**,dist/**,build/**

sonar.javascript.node.maxspace=6144